name: opening_hours
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.12.1
  url_launcher: ^5.4.11
  path_provider: ^1.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  geolocator: ^5.1.3
  flappy_search_bar: ^1.7.2
  intl: ^0.16.1


dev_dependencies:
  google_fonts: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - config/